# Generated by Django 6.0.6 on 2026-07-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="film",
            name="fragman_link",
        ),
    ]
