# Generated by Django 6.0.6 on 2026-07-08 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_remove_film_fragman_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="puan",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0.0, message="Puan en az 0 olabilir."
                    ),
                    django.core.validators.MaxValueValidator(
                        5.0, message="Puan en fazla 5 olabilir."
                    ),
                ]
            ),
        ),
    ]
