# Generated by Django 6.0.6 on 2026-07-08 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Yonetmen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=100)),
                ("biyografi", models.TextField(blank=True, null=True)),
                (
                    "fotograf",
                    models.ImageField(blank=True, null=True, upload_to="yonetmenler/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=200)),
                ("tur", models.CharField(max_length=50)),
                ("puan", models.FloatField()),
                (
                    "afis",
                    models.ImageField(blank=True, null=True, upload_to="afisler/"),
                ),
                ("ozet", models.TextField(blank=True, null=True)),
                (
                    "fragman_link",
                    models.URLField(
                        blank=True,
                        help_text="YouTube Video Linki (Örn: https://www.youtube.com/watch?v=...)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "yonetmen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filmler",
                        to="movies.yonetmen",
                    ),
                ),
            ],
        ),
    ]
