# Generated by Django 6.0.6 on 2026-07-09 08:49

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "movies",
            "0005_film_arkaplan_resmi_film_fragman_url_film_imdb_puani_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Oyuncu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "isim",
                    models.CharField(
                        max_length=100, validators=[movies.models.validate_letters_only]
                    ),
                ),
                ("biyografi", models.TextField(blank=True, null=True)),
                (
                    "fotograf",
                    models.ImageField(blank=True, null=True, upload_to="oyuncular/"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="film",
            name="oyuncular",
            field=models.ManyToManyField(
                blank=True, related_name="filmler", to="movies.oyuncu"
            ),
        ),
    ]
