# Generated by Django 6.0.6 on 2026-07-09 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_oyuncu_film_oyuncular"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="film",
            name="arkaplan_resmi",
        ),
    ]
