# Generated by Django 6.0.6 on 2026-07-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Yazı",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=200)),
                ("icerik", models.TextField()),
                ("kategori", models.CharField(max_length=100)),
                ("tarih", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
