# Generated by Django 6.0.6 on 2026-07-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="yazı",
            name="gorsel",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog_gorselleri/"
            ),
        ),
    ]
