# Generated by Django 6.0.6 on 2026-07-08 13:36

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_film_puan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="baslik",
            field=models.CharField(
                max_length=200, validators=[movies.models.validate_no_digits]
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="tur",
            field=models.CharField(
                max_length=50, validators=[movies.models.validate_letters_only]
            ),
        ),
        migrations.AlterField(
            model_name="yonetmen",
            name="isim",
            field=models.CharField(
                max_length=100, validators=[movies.models.validate_letters_only]
            ),
        ),
    ]
