# Generated by Django 6.0.6 on 2026-07-08 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_alter_film_baslik_alter_film_tur_alter_yonetmen_isim"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="arkaplan_resmi",
            field=models.ImageField(blank=True, null=True, upload_to="arkaplanlar/"),
        ),
        migrations.AddField(
            model_name="film",
            name="fragman_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="film",
            name="imdb_puani",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.0, message="IMDb Puanı en az 0.0 olabilir."
                    ),
                    django.core.validators.MaxValueValidator(
                        10.0, message="IMDb Puanı en fazla 10.0 olabilir."
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="sure",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="film",
            name="yayin_yili",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
